var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/testimonials/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0nrdgip._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0qvysv~.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/_0fflnno._.js")
R.c("server/chunks/ssr/_0v1pk81._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0zq0aps._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__01d4g7h._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_testimonials_page_actions_0qj2nuk.js")
R.m(40594)
module.exports=R.m(40594).exports
